Frontends/SeriesDictionary.WebUI/Controllers/MainPageController.cs
using Microsoft.AspNetCore.Mvc;

namespace SeriesDictionary.WebUI.Controllers
{
    public class MainPageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Frontends/SeriesDictionary.WebUI/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SeriesDictionary.Application.Features.Mediator.Results.EpisodeResults;
using SeriesDictionary.Application.Features.Mediator.Results.ListShowResults;
using SeriesDictionary.Dto.MovieDto;
using SeriesDictionary.Dto.MovieDto.SeriesDictionary.Application.DTOs;


namespace SeriesDictionary.WebUI.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public MoviesController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }
        public async Task<IActionResult> Index()
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync("https://localhost:7257/api/Show/movies");
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<List<GetMovieQueryResult>>(jsonData);
                return View(values);
            }
            return View();
        }


        public async Task<IActionResult> Details(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync($"https://localhost:7257/api/Show/details/{id}");

            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var showDetail = JsonConvert.DeserializeObject<ShowDetailsViewModel>(jsonData, new JsonSerializerSettings
                {
                    ReferenceLoopHandling = ReferenceLoopHandling.Ignore // Döngüsel referansları ihmal et
                });

                ViewData["EpisodeId"] = id; // EpisodeId'yi ViewData ile gönder
                return View(showDetail);
            }

            return View(new ShowDetailsViewModel()); // Boş bir model döndür
        }


    }
}

Frontends/SeriesDictionary.WebUI/Controllers/QuizSeriesController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SeriesDictionary.Application.Features.Mediator.Results.EpisodeResults;
using SeriesDictionary.Application.Features.Mediator.Results.ListShowResults;

namespace SeriesDictionary.WebUI.Controllers
{
    public class QuizSeriesController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public QuizSeriesController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IActionResult> Index()
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync("https://localhost:7257/api/Show/seriesandmovies");
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<List<GetSeriesAndMoviesQueryResult>>(jsonData);
                return View(values);
            }
            return View();
        }

        public async Task<IActionResult> Details(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync($"https://localhost:7257/api/Show/details/{id}");

            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var showDetail = JsonConvert.DeserializeObject<ShowDetailsViewModel>(jsonData, new JsonSerializerSettings
                {
                    ReferenceLoopHandling = ReferenceLoopHandling.Ignore // Döngüsel referansları ihmal et
                });

                return View(showDetail);
            }

            return View(new ShowDetailsViewModel()); // Boş bir model döndür
        }
    }
}

Frontends/SeriesDictionary.WebUI/Controllers/SeriesController.cs
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json; // Newtonsoft.Json kullanımı
using SeriesDictionary.Application.Features.Mediator.Results.EpisodeResults;
using SeriesDictionary.Application.Features.Mediator.Results.ListShowResults;
using SeriesDictionary.Dto.SeriesDto;

namespace SeriesDictionary.WebUI.Controllers
{
    public class SeriesController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public SeriesController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IActionResult> Index()
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync("https://localhost:7257/api/Show/series");
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<List<GetSeriesQueryResult>>(jsonData);
                return View(values);
            }
            return View();
        }

        public async Task<IActionResult> Details(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync($"https://localhost:7257/api/Show/details/{id}");

            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var showDetail = JsonConvert.DeserializeObject<ShowDetailsViewModel>(jsonData, new JsonSerializerSettings
                {
                    ReferenceLoopHandling = ReferenceLoopHandling.Ignore // Döngüsel referansları ihmal et
                });

                return View(showDetail);
            }

            return View(new ShowDetailsViewModel()); // Boş bir model döndür
        }


    }
}

Frontends/SeriesDictionary.WebUI/Views/Layout/Index.cshtml
@{
    Layout = null;
}

<!-- /*
* Template Name: Blogy
* Template Author: Untree.co
* Template URI: https://untree.co/
* License: https://creativecommons.org/licenses/by/3.0/
*/ -->
<!doctype html>
<html lang="en">
﻿
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="author" content="Untree.co">
	<link rel="shortcut icon" href="~/blogy-1.0.0/favicon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

	<meta name="description" content="" />
	<meta name="keywords" content="bootstrap, bootstrap5" />

	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;600;700&display=swap" rel="stylesheet">


	<link rel="stylesheet" href="~/blogy-1.0.0/fonts/icomoon/style.css">
	<link rel="stylesheet" href="~/blogy-1.0.0/fonts/flaticon/font/flaticon.css">

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

	<link rel="stylesheet" href="~/blogy-1.0.0/css/tiny-slider.css">
	<link rel="stylesheet" href="~/blogy-1.0.0/css/aos.css">
	<link rel="stylesheet" href="~/blogy-1.0.0/css/glightbox.min.css">
	<link rel="stylesheet" href="~/blogy-1.0.0/css/style.css">

	<link rel="stylesheet" href="~/blogy-1.0.0/css/flatpickr.min.css">


	<title>Series Dictionary</title>
    <style>
        #difficultyButtons {
            display: flex;
            justify-content: space-between; /* Aralarındaki mesafeyi dengelemek için */
            gap: 10px; /* Butonlar arasına eşit boşluk ekler */
        }
    </style>
</head>
<body>

	<div class="site-mobile-menu site-navbar-target">
		<div class="site-mobile-menu-header">
			<div class="site-mobile-menu-close">
				<span class="icofont-close js-menu-toggle"></span>
			</div>
		</div>
		<div class="site-mobile-menu-body"></div>
	</div>
    
	﻿
	<div class="site-mobile-menu site-navbar-target">
		<div class="site-mobile-menu-header">
			<div class="site-mobile-menu-close">
				<span class="icofont-close js-menu-toggle"></span>
			</div>
		</div>
		<div class="site-mobile-menu-body"></div>
	</div>

	<nav class="site-nav">
		<div class="container">
			<div class="menu-bg-wrap">
				<div class="site-navigation">
					<div class="row g-0 align-items-center">
						<div class="col-2">


                            <a href="index.html" class="logo m-0 float-start">
                                <i class="bi bi-book" style="font-size: 30px; color: #007bff;"></i>
                                <span style="font-size: 20px; font-weight: bold; color: #333; position: relative; top: -5px;">Dizi Sözlük</span>
                            </a>

					</div>
						<div class="col-8 text-center">
							<form action="#" class="search-form d-inline-block d-lg-none">
								<input type="text" class="form-control" placeholder="Search...">
								<span class="bi-search"></span>
							</form>

							<ul class="js-clone-nav d-none d-lg-inline-block text-start site-menu mx-auto">
                                <li class="active"><a href="@Url.Action("Index", "MainPage")">AnaSayfa</a></li>
                                <li><a href="@Url.Action("Index", "Series")">Dizi Listesi</a></li>
                                <li><a href="@Url.Action("Index", "Movies")">Film Listesi</a></li>


                                <li><a href="@Url.Action("Index", "Contact")">İletisim</a></li>
                                <li><a href="@Url.Action("Index", "Movies")">Kelimelerim</a></li>
                                <li><a href="@Url.Action("Index", "QuizSeries")">Quiz</a></li>

                                <li><a href="/Writer/Dashboard/Index/">Panel</a></li>
                                <li>
                                    <a href="#" onclick="document.getElementById('logout-form').submit();">Çıkış Yap</a>
                                    <form id="logout-form" asp-action="Logout" asp-controller="Login" method="post" style="display: none;"></form>
                                </li>

							</ul>

						</div>
										<div class="col-2 text-end">
						<a href="#" class="burger ms-auto float-end site-menu-toggle js-menu-toggle d-inline-block d-lg-none light">
							<span></span>
						</a>
                            <form action="#" class="search-form d-none d-lg-inline-block" style="margin-left: 30px;">
                                <input type="text" class="form-control" placeholder="Dizi Ara...">
                                <span class="bi-search"></span>
                            </form>

					</div>
					</div>
				</div>
			</div>
		</div>
	</nav>

    @RenderBody()

    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="widget">
                        <h3 class="mb-4">Hakkımızda</h3>
                        <p>Uzak uzak diyarlarda birbirinden yetenekli blogger ve yazarlarımızla güncel ve ilgi çekici konularda içerik üretmeye devam ediyoruz.</p>
                    </div> <!-- /.widget -->
                    <div class="widget">
                        <h3>Social</h3>
                        <ul class="list-unstyled social">
                            <li><a href="#"><span class="icon-instagram"></span></a></li>
                            <li><a href="#"><span class="icon-twitter"></span></a></li>
                            <li><a href="#"><span class="icon-facebook"></span></a></li>
                            <li><a href="#"><span class="icon-linkedin"></span></a></li>
                            <li><a href="#"><span class="icon-pinterest"></span></a></li>
                            <li><a href="#"><span class="icon-dribbble"></span></a></li>
                        </ul>
                    </div> <!-- /.widget -->
                </div> <!-- /.col-lg-4 -->
                <div class="col-lg-4 ps-lg-5">
                    <div class="widget">
                        <h3 class="mb-4">Şirketimiz</h3>
                        <ul class="list-unstyled float-start links">
                            <li><a href="#">Hakkımızda</a></li>
                            <li><a href="#">Hizmetler</a></li>
                            <li><a href="#">Vizyonumuz</a></li>
                            <li><a href="#">Misyonumuz</a></li>
                            <li><a href="#">Şartlar Kurallar</a></li>
                            <li><a href="#">Güvenlik</a></li>
                        </ul>
                        <ul class="list-unstyled float-start links">
                            <li><a href="#">Partnerlerimiz</a></li>
                            <li><a href="#">Reklam</a></li>
                            <li><a href="#">Kariyer</a></li>
                            <li><a href="#">Bloglar</a></li>
                            <li><a href="#">Sıkça Sorulanlar</a></li>
                            <li><a href="#">Giriş Yap</a></li>
                        </ul>
                    </div> <!-- /.widget -->
                </div> <!-- /.col-lg-4 -->
                <div class="col-lg-4">
                    <div class="widget">
                        <h3 class="mb-4">Recent Post Entry</h3>
                        <div class="post-entry-footer">
                            <ul>
                                <li>
                                    <a href="">
                                        <img src="images/img_1_sq.jpg" alt="Image placeholder" class="me-4 rounded">
                                        <div class="text">
                                            <h4>There’s a Cool New Way for Men to Wear Socks and Sandals</h4>
                                            <div class="post-meta">
                                                <span class="mr-2">March 15, 2018 </span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="">
                                        <img src="images/img_2_sq.jpg" alt="Image placeholder" class="me-4 rounded">
                                        <div class="text">
                                            <h4>There’s a Cool New Way for Men to Wear Socks and Sandals</h4>
                                            <div class="post-meta">
                                                <span class="mr-2">March 15, 2018 </span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="">
                                        <img src="images/img_3_sq.jpg" alt="Image placeholder" class="me-4 rounded">
                                        <div class="text">
                                            <h4>There’s a Cool New Way for Men to Wear Socks and Sandals</h4>
                                            <div class="post-meta">
                                                <span class="mr-2">March 15, 2018 </span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </div>


                    </div> <!-- /.widget -->
                </div> <!-- /.col-lg-4 -->
            </div> <!-- /.row -->

            <div class="row mt-5">
                <div class="col-12 text-center">
                    <!--
                        **==========
                        NOTE:
                        Please don't remove this copyright link unless you buy the license here https://untree.co/license/
                        **==========
                      -->

                    <p>
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script>. All Rights Reserved. &mdash; Designed with love by <a href="https://untree.co">Untree.co</a>  Distributed by <a href="https://themewagon.com">ThemeWagon</a> <!-- License information: https://untree.co/license/ -->
                    </p>
                </div>
            </div>
        </div> <!-- /.container -->
    </footer>
	<!-- Preloader -->
    <div id="overlayer"></div>
    <div class="loader">
        <div class="spinner-border text-primary" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>


    <script src="~/blogy-1.0.0/js/bootstrap.bundle.min.js"></script>
    <script src="~/blogy-1.0.0/js/tiny-slider.js"></script>

    <script src="~/blogy-1.0.0/js/flatpickr.min.js"></script>


    <script src="~/blogy-1.0.0/js/aos.js"></script>
    <script src="~/blogy-1.0.0/js/glightbox.min.js"></script>
    <script src="~/blogy-1.0.0/js/navbar.js"></script>
    <script src="~/blogy-1.0.0/js/counter.js"></script>
    <script src="~/blogy-1.0.0/js/custom.js"></script>


</body>
</html>